### ISSUE TITLE
History project has too few articles

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1_selection_tools#13]
It should have around 50K article according to https://en.wikipedia.org/wiki/Wikipedia:WikiProject_History
But we have only 1,5K of then according:
```
curl https://ftp.nluug.nl/pub/kiwix/wp1/enwiki_2019-03/projects/History | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27600  100 27600    0     0   230k      0 --:--:-- --:--:-- --:--:--  230k
   1582    1582   27600
```
Maybe the problem only occurs with ``meta projects`` or maybe we have a gatering problem.

**Comment by Popolechien** [comment]
Yep, it is for instance missing [Real Madrid CF](https://en.wikipedia.org/wiki/Real_Madrid_CF) and [France national football team](https://en.wikipedia.org/wiki/France_national_football_team)

**Comment by kelson42** [comment]
Should be fixe now.
