### ISSUE TITLE
Undue weight in Football selection

### ISSUE THREAD

**Issue by Popolechien** [openzim/wp1_selection_tools#16]
The current landing page for the football selection lists the Peruvian National Team in the Top100 articles, whereas top teams like Brazil, France or Germany are not listed.

Other unlikely top performers are the Millenium stadium (in Cardiff), CenturyLink Field (in Seattle), Celtic Park (in Glasgow), whereas Camp Nou, Santiago Bernabeu or Emirates Stadium are missing.

Similarly, Major League Soccer is in, whereas the Premier League, La Liga or the Bundesliga are not.

**Comment by Popolechien** [comment]
Ok, I don't know if the algorithm has changed since the ticket was open but the latest football landing page in Spanish (wikipedia_es_football_nopic_2019-05) shows mostly _German_ clubs or otherwise entirely irrelevant articles: I would think that people are more interested in Messi and the current Champions' League than in an obscure Finnish footballer or the 2008-09 Bundesliga season- yet Aapo Mäenpää is on the landing page and Messi is not (ditto for the leagues);
1. Can we for the time being forget all sorting attempt for sports-related selections;
2. Can we generate selections based on traffic reports _by language_? (e.g. Spanish selection's landing page would be based on Spanish Wikipedia's traffic)?

![Capture d’écran 2019-05-21 à 12 16 03](https://user-images.githubusercontent.com/21675885/58101400-d4d28280-7bdf-11e9-8af0-b37b721bb74b.png)

**Comment by Popolechien** [comment]
Just checked and all language version have a different landing page ([es](http://library.kiwix.org/wikipedia_es_football_novid_2019-05/A/index), [ru](http://library.kiwix.org/wikipedia_ru_football_nopic_2019-05/A/index), [ar](http://library.kiwix.org/wikipedia_ar_football_novid_2019-05/A/index), [zh](http://library.kiwix.org/wikipedia_zh_football_nopic_2019-05/A/index)), yet all of them manage to be largely irrelevant (except maybe the [German one](http://library.kiwix.org/wikipedia_de_football_novid_2019-05/A/index), which is 80% German-centered but with none of the current leaders, e.g. Bayern or BvB). 
We **definitely** should stick to most popular for sports landing pages.

**Comment by Popolechien** [comment]
As complement to the above, I realize there is also a strong bias towards articles starting with a number:
![screenshots](https://user-images.githubusercontent.com/21675885/62948839-67e91600-bde5-11e9-8d7c-90e2ac5fce75.jpg)

**Comment by kelson42** [comment]
The problem was that the projects and custom selection translated versions where not sorted descending by score. This has been fixed.
