### ISSUE TITLE
Are Tops sorted based on language?

### ISSUE THREAD

**Issue by rgaudin** [openzim/wp1_selection_tools#19]
From the introduction @kelson42 gave at Wikimania, `tops` selection is produced for the English WP. Other languages tops represent a list of the localized-version of its articles.

If so, how is the sorting done on the tops ? `enwiki`'s first article is `Bird` while `frwiki`'s one is `France`.

**Comment by kelson42** [comment]
Yes, TOP list articles are sorted descending by their article respective scores... and the score depends only on local wiki things.
