### ISSUE TITLE
Share of total pageviews for TOP selection

### ISSUE THREAD

**Issue by Popolechien** [openzim/wp1_selection_tools#21]
The aim of TOP is to offer the most relevant experience to the user by making an educated guess at what they would like to see. 
Is there an easy(-ish) way to measure what share of (average) monthly pageviews that would be covered by TOP?

**Comment by kelson42** [comment]
@Popolechien I don't understand the question. Everything we publish is here https://download.kiwix.org/wp1/, README included. We don't provide monthly Wikipedia pageviews as this is the role of Wikimedia which does it.

**Comment by kelson42** [comment]
@Popolechien I think I understand the question now... the answer is no. But the maths can be done on the data provided by the WP1 data.
