### ISSUE TITLE
Indonesian TOP selection is irrelevant

### ISSUE THREAD

**Issue by Popolechien** [openzim/wp1_selection_tools#22]
Currently the first 30 articles from wikipedia_id_top_maxi_2019-08.zim are lists of rural French cities by department.
I doubt this ever would feature in the at the top of the top 50,000 most interesting articles for Bahasa speakers.
Until we have something without so many false positive it simply would make more sense to use the top most read articles, without trying to curate these.
![Capture d’écran 2019-08-27 à 15 24 26](https://user-images.githubusercontent.com/21675885/63775085-e910d480-c8de-11e9-83d1-7cb841033835.png)

**Comment by kelson42** [comment]
Strongly suspect this is because of #6

**Comment by kelson42** [comment]
@Popolechien I had a look accurately to that silly result and came to the conclusion that everything works as intended and I have no real good idea how to do it better. What the WPID contributors have made is that they have created redirects for each French village to this kind of articles (villages in departement XYZ). As a consequence the KPI of all the redirects are added to the targeted articles (number of pageviews, lang links, page links)... and all these indicators are as a consequence really high. Even if I would take only the pageviews, they would probably still stay quite on the top.

**Comment by kelson42** [comment]
The pageviews work better than I thought first. I have tweaked the algorithm to make them more proeminent in the final score and the result is a lot better.
