### ISSUE TITLE
Does the TOP selection include all elements of Vital selection?

### ISSUE THREAD

**Issue by Popolechien** [openzim/wp1_selection_tools#24]
We have https://download.kiwix.org/wp1/enwiki/vital.lzma, but is it hard-included in the Top selection, or are these articles only included to the selection if they reach a score threshold?

Or to put it differently, are these 10,000 articles (the vital list) out 50,000 included no matter what? Is this the case for every language for which we produce a Top selection? (I'm not sure Arabic and Chinese readers care much about Jane Austen or Dostoievsky)

**Comment by kelson42** [comment]
@Popolechien Vital and TOP lists are two different lists with their own properties. 3581 of vitals are in the TOP 10000 list. So, answer is NO.
