### ISSUE TITLE
Add "WikiProject Spaceflight" to "wikipedia_en_astronomy.zim"

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/wp1_selection_tools#30]
Please add: **[WikiProject Spaceflight](https://en.wikipedia.org/wiki/Category:WikiProject_Spaceflight)** to the **wikipedia_en_astronomy.zim**.

**Comment by kelson42** [comment]
For the moment, I'm not really convinced this belong together in that ZIM honestly.

**Comment by Ubuntu-2020** [comment]
@kelson42 I'm sure!
Here are some examples: the Rovers **[Spirit](https://en.wikipedia.org/wiki/Spirit_(rover))**, **[Curiosity](https://en.wikipedia.org/wiki/Curiosity_(rover))** and **[Mars 2020](https://en.wikipedia.org/wiki/Mars_2020)**. None of these articles are in **wikipedia_en_astronomy.zim**.
Aren't these articles related to astronomy?
[**WikiProject Astronomy**](https://en.wikipedia.org/wiki/Category:WikiProject_Astronomy)‎ and **[WikiProject Spaceflight‎](https://en.wikipedia.org/wiki/Category:WikiProject_Spaceflight)** is part of **[Space WikiProjects](https://en.wikipedia.org/wiki/Category:Space_WikiProjects)**.

**Comment by kelson42** [comment]
Spaceflights and astronomy are two different things, this is why there is two different w8kiprojects. Maybe we should make a “space” zim file in place of astronomy @Ubuntu-2020 @Popolechien?

**Comment by Popolechien** [comment]
@kelson42 I have no opinion one way or another. Do we have an idea of what the size of the combined projects would be (number of articles, zim file size)?
