### ISSUE TITLE
Monthly .tsv lists are not being created since Feb 1's enwiki-2021-02 

### ISSUE THREAD

**Issue by holta** [openzim/wp1_selection_tools#34]
`enwiki-2021-02` from February 1st is the latest here:

http://download.openzim.org/wp1/

Does anybody know why the monthly creation of .tsv lists in English is no longer working?

**Comment by kelson42** [comment]
Fixed with https://github.com/openzim/wp1_selection_tools/commit/ee4ba87a8154715881e7a412fb7eb8c5e3f1c9e6
