### ISSUE TITLE
missing march medicine.tsv

### ISSUE THREAD

**Issue by tim-moody** [openzim/wp1_selection_tools#47]
sorry if this is the wrong place to report this, but I don't see medicine.tsv for 2024_03:

```
https://download.openzim.org/wp1/

[enwiki_2023-12/](https://download.openzim.org/wp1/enwiki_2023-12/)                                    01-Dec-2023 14:33       -
[enwiki_2024-01/](https://download.openzim.org/wp1/enwiki_2024-01/)                                    01-Jan-2024 13:33       -
[enwiki_2024-02/](https://download.openzim.org/wp1/enwiki_2024-02/)                                    01-Feb-2024 13:44       -

[eowiki_2022-04/](https://download.openzim.org/wp1/eowiki_2022-04/)                                    22-Apr-2022 19:13
```

**Comment by kelson42** [comment]
Investigating... nothing obvious for the moment... I have restarted the process manually to see if something will happen.

Important to notice is that this piece of software as reached its EOL. @audiodude is rewritting it in Python and integrating it to the WP1 engine.

**Comment by tim-moody** [comment]
>Important to notice is that this piece of software as reached its EOL. @audiodude is rewritting it in Python and integrating it to the WP1 engine.

Great news.

**Comment by kelson42** [comment]
There is somekind of SQL error... not even sure this is the only problem...

**Comment by kelson42** [comment]
It seems the problem fixed by itself! http://download.openzim.org/wp1/enwiki_2024-04/customs/medicine.tsv
