### ISSUE TITLE
Add .tsv at the end of the files

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1_selection_tools#9]

**Comment by kelson42** [comment]
@rgaudin Would that be a big deal to update the Zim farm --articleList values?

**Comment by rgaudin** [comment]
On all of them? Not a problem but:

* why ?
* Is .tsv appropriate as this usually mean tab-separates values while to my understanding those files contain juste one article per line. Could be considered a single column tsv .. without header row though.
* I think we added support for extension in this file url in mwoffliner (so it’s not included in zim flame) but I’m not sure. can you confirm ?

**Comment by kelson42** [comment]
>     * why ?

To clarify the format of the files
 
>     * Is .tsv appropriate as this usually mean tab-separates values while to my understanding those files contain juste one article per line. Could be considered a single column tsv .. without header row though.

Yes is is appropriate and it is true that a few files have only one column.

>     * I think we added support for extension in this file url in mwoffliner (so it’s not included in zim flame) but I’m not sure. can you confirm ?

Good point that I had forgotten. Should perfectly work, Have fixed a bug around this myself a few months. ago.

**Comment by rgaudin** [comment]
Changed in 199 schedules.
